name: melnet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.3
  #- nvidia-apex
  - pysoundfile
  - matplotlib
  - librosa=0.7
  - torchaudio
  - torchvision

# conda env update -f environment.yml --prune